var subjectObject = {
  UNGA: [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Bahrain",
    "Bangladesh",
    "Belarus",
    "Belgium",
    "Belize",
    "Botswana",
    "Brazil",
    "Bulgaria",
    "Burkina faso",
    "Canada",
    "Central African Republic",
    "Chile",
    "China",
    "Colombia",
    "Cuba",
    "Czech Republic",
    "Denmark",
    "Egypt",
    "Estonia",
    "Ethiopia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Indonesia",
    "Iraq",
    "Ireland",
    "Islamic Republic of Iran",
    "Israel",
    "Italy",
    "Japan",
    "Jordan",
    "Kenya",
    "Kuwait",
    "Latvia",
    "Lebanon",
    "Libya",
    "Lithuania",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Moldova",
    "Mongolia",
    "Morocco",
    "Myanmar",
    "Netherlands",
    "New Zealand",
    "Nigeria",
    "Norway",
    "Oman",
    "Pakistan",
    "Palestine(O)",
    "Philippines",
    "Poland",
    "Portugal",
    "Romania",
    "Russian Federation",
    "San Marino",
    "Saudi Arabia",
    "Sierra leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Sweden",
    "Syrian arab republic",
    "Tajikistan",
    "Turkey",
    "Ukraine",
    "United Kingdom",
    "United States Of America",
    "Uzbekistan",
    "Venezuela",
    "Vietnam",
    "Yemen",
  ],
  UNCSW: [
    "Afghanistan",
    "Algeria",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Bangladesh",
    "Belarus",
    "Brazil",
    "Colombia",
    "Comoros",
    "Congo",
    "Cuba",
    "Denmark",
    "Dominican",
    "Republic",
    "Ecuador",
    "Equatorial Guinea",
    "Germany",
    "Ghana",
    "Haiti",
    "India",
    "Iraq",
    "Israel",
    "Japan",
    "Kenya",
    "Latvia",
    "Malaysia",
    "Mexico",
    "Mongolia",
    "Morocco",
    "Nicaragua",
    "Nigeria",
    "Philippines",
    "Republic of Korea",
    "Russian Federation",
    "Saudi Arabia",
    "Senegal",
    "Somalia",
    "South Africa",
    "Switzerland",
    "Togo",
    "Turkey",
    "Turkmenistan",
    "United States",
    "Zambia",
  ],
  WHO: [
    "Afghanistan",
    "Argentina",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Belarus",
    "Belgium",
    "Bhutan",
    "Brazil",
    "Bulgaria",
    "Burkina Faso",
    "Cameroon",
    "Chile ",
    "China",
    "Cuba",
    "Czech Republic",
    "Dem. Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominican Republic",
    "Ecuador",
    "El Salvador",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Germany",
    "Greece ",
    "Guatemala ",
    "Hungary",
    "India",
    "Indonesia",
    "Ireland",
    "Israel",
    "Italy ",
    "Japan",
    "Kenya",
    "Kyrgyzstan ",
    "Libya",
    "Lithuania ",
    "Mexico ",
    "Mongolia",
    "Morocco",
    "Netherlands",
    "New Zealand",
    "Nigeria",
    "Norway",
    "Oman",
    "Pakistan",
    "Poland",
    "Portugal",
    "Qatar",
    "Republic of Korea ",
    "Romania",
    "Russian Federation",
    "Rwanda",
    "South Africa",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Sweden",
    "Switzerland",
    "Syrian Arab Republic",
    "Tajikistan",
    "Thailand",
    "Tunisia",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom ",
    "United States of America",
    "Vietnam",
    "Yemen",
  ],
  UNHRC: [
    "Afghanistan (O)",
    "Argentina",
    "Armenia",
    "Australia (O)",
    "Austria",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados (O)",
    "Belgium (O)",
    "Bolivia",
    "Brazil",
    "Bulgaria",
    "Burkina Faso",
    "Canada (O)",
    "Cameroon",
    "China",
    "Côte d’Ivoire",
    "Chad(O)",
    "Chile (O)",
    "Colombia (O)",
    "Costa Rica (O)",
    "Croatia (O)",
    "Cuba",
    "Czech Republic",
    "Democratic People's Republic of Korea (O)",
    "Democratic Republic of the Congo (O)",
    "Denmark",
    "Eritrea",
    "Egypt (O)",
    "Fiji",
    "Finland (O)",
    "France",
    "Germany",
    "Gabon",
    "Hungary (O)",
    "Iceland (O)",
    "India",
    "Indonesia",
    "Islamic Republic of Iran (O)",
    "Italy",
    "Jamaica (O)",
    "Japan",
    "Kenya (O)",
    "Libya",
    "Lithuania (O)",
    "Luxembourg (O)",
    "Macedonia (O)",
    "Malawi",
    "Marshall Islands",
    "Malaysia (O)",
    "Mexico (O)",
    "Myanmar (O)",
    "Namibia",
    "Nepal",
    "Netherlands",
    "New Zealand (O)",
    "Norway (O)",
    "Pakistan",
    "Paraguay (O)",
    "Peru (O)",
    "Philippines",
    "Poland",
    "Portugal (O)",
    "Qatar (O)",
    "Republic of Korea",
    "Romania (O)",
    "Russian Federation",
    "Senegal",
    "Saudi Arabia (O)",
    "Slovakia (O)",
    "Solomon Islands (O)",
    "Somalia",
    "South Africa (O)",
    "Spain (O)",
    "Sri Lanka (O)",
    "Sudan",
    "Sweden (O)",
    "Switzerland (O)",
    "Syrian Arab Republic (O)",
    "Togo",
    "Thailand (O)",
    "Turkey (O)",
    "Ukraine",
    "United Kingdom",
    "United States of America (O)",
    "Uruguay",
    "Uzbekistan",
    "Venezuela (Bolivarian Republic of)",
  ],
  UNSC: [
    "United States of America",
    "China",
    "France",
    "United Kingdom",
    "Russia",
    "Estonia",
    "India ",
    "Ireland",
    "Kenya ",
    "Mexico ",
    "Niger ",
    "Norway",
    "Saint Vincent and the Grenadines ",
    "Tunisia ",
    "Vietnam ",
    "Germany (O)",
    "Iraq (O)",
    "Japan (O)",
    "Malaysia (O)",
    "Myanmar (O)",
    "Netherlands (O)",
    "New Zealand (O)",
    "Pakistan (O)",
    "Poland (O)",
    "Spain (O)",
  ],
  UNFCCC: [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Bahrain",
    "Bangladesh",
    "Belarus",
    "Belgium",
    "Belize",
    "Botswana",
    "Brazil",
    "Bulgaria",
    "Burkina Faso",
    "Canada",
    "Central African Republic",
    "Chile",
    "China",
    "Colombia",
    "Cuba",
    "Czech Republic",
    "Denmark",
    "Egypt",
    "Estonia",
    "Ethiopia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Indonesia",
    "Iraq",
    "Ireland",
    "Islamic Republic of Iran",
    "Israel",
    "Italy",
    "Japan",
    "Jordan",
    "Kenya",
    "Kuwait",
    "Latvia",
    "Lebanon",
    "Libya",
    "Lithuania",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Moldova",
    "Mongolia",
    "Morocco",
    "Myanmar",
    "Netherlands",
    "New Zealand",
    "Nigeria",
    "Norway",
    "Oman",
    "Pakistan",
    "Palestine(O)",
    "Philippines",
    "Poland",
    "Portugal",
    "Romania",
    "Russian Federation",
    "San Marino",
    "Saudi Arabia",
    "Sierra leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Sweden",
    "Syrian arab republic",
    "Tajikistan",
    "Turkey",
    "Ukraine",
    "United Kingdom",
    "United States Of America",
    "Uzbekistan",
    "Venezuela",
    "Vietnam",
    "Yemen",
  ],
  "NITI Aayog": [
    "Admiral D K Joshi ",
    "Amitabh Kant",
    "Dr Virendra Kumar",
    "Dr. Tamilisai Soundararajan",
    "Dr. V. K. Paul",
    "Km. Mamata Banerjee",
    "Nitin Gadkari",
    "Prof. Ramesh Chand",
    "Shri Amit Shah",
    "Shri Anil Baijal ",
    "Shri Arvind Kejriwal",
    "Shri Ashok Gehlot",
    "Shri Ashwini Vaishnaw",
    "Shri Banwarilal Purohit ",
    "Shri Bhupendra Patel",
    "Shri Bhupesh Baghel",
    "Shri Biplab Kumar Deb",
    "Shri Charanjit Singh Channi",
    "Shri Conrad Kongkal Sangma",
    "Shri Hemant Soren",
    "Shri Himanta Biswa Sarma",
    "Shri Jairam Thakur",
    "Shri K Chandrasekhar Rao",
    "Shri M. K. Stalin",
    "Shri Manohar Lal",
    "Shri Manoj Sinha ",
    "Shri N. Biren Singh",
    "Shri N. Rangaswamy",
    "Shri Narendra Singh Tomar",
    "Shri Naveen Patnaik",
    "Shri Neiphiu Rio",
    "Shri Nitish Kumar",
    "Shri Pema Khandu",
    "Shri Pinarayi Vijayan",
    "Shri Piyush Goyal",
    "Shri Praful Patel ",
    "Shri Pramod Sawant",
    "Shri PS Golay",
    "Shri Pu Zoramthanga",
    "Shri Pushkar Singh Dhami",
    "Shri Radha Krishna Mathur ",
    "Shri Rajnath Singh",
    "Shri Rao Inderjit Singh",
    "Shri Shivraj Singh Chouhan",
    "Shri Uddhav Thackeray",
    "Shri V. K. Saraswat",
    "Shri Yogi Aditya Nath",
    "Shri YS Jagan Mohan Reddy",
    "Smt Nirmala Sitharaman",
    "Sri Basavaraj Bommai",
  ],
  ICJ: [
    "President Joan E. Donoghue",
    "Vice-President Kirill Gevorgian",
    "Judge Abdulqawi Ahmed Yusuf",
    "Judge Antônio Augusto Cancado Trindade",
    "Judge Dalveer Bhandari",
    "Judge Georg Nolte",
    "Judge Iwasawa Yuji",
    "Judge Julia Sebutinde",
    "Judge Mohamed Bennouna",
    "Judge Nawaf Salam",
    "Judge Patrick Lipton Robinson",
    "Judge Peter Tomka",
    "Judge Ronny Abraham",
    "Judge Xue Hanqin",
  ],
  IP: ["Caricaturist", "Reporter"],
};

window.onload = function () {
  var one_1 = document.getElementById("one-1");
  var one_2 = document.getElementById("one-2");

  var two_1 = document.getElementById("two-1");
  var two_2 = document.getElementById("two-2");

  var three_1 = document.getElementById("three-1");
  var three_2 = document.getElementById("three-2");

  for (var x in subjectObject) {
    one_1.options[one_1.options.length] = new Option(x, x);
  }

  one_1.onchange = function () {
    //empty Chapters- and Topics- dropdowns
    one_2.length = 1;
    //display correct values
    for (var y in subjectObject[this.value]) {
      var z = subjectObject[this.value][y];
      one_2.options[one_2.options.length] = new Option(z, z);
    }
  };

  for (var x in subjectObject) {
    two_1.options[two_1.options.length] = new Option(x, x);
  }

  two_1.onchange = function () {
    //empty Chapters- and Topics- dropdowns
    two_2.length = 1;
    //display correct values
    for (var y in subjectObject[this.value]) {
      var z = subjectObject[this.value][y];
      two_2.options[two_2.options.length] = new Option(z, z);
    }
  };

  for (var x in subjectObject) {
    three_1.options[three_1.options.length] = new Option(x, x);
  }

  three_1.onchange = function () {
    //empty Chapters- and Topics- dropdowns
    three_2.length = 1;
    //display correct values
    for (var y in subjectObject[this.value]) {
      var z = subjectObject[this.value][y];
      three_2.options[three_2.options.length] = new Option(z, z);
    }
  };
};

document.getElementById("yes").addEventListener("click", () => {
  document.getElementById("enrollment").style.display = "block";
  document.getElementById("enrollment-label").style.display = "block";
});

document.getElementById("no").addEventListener("click", () => {
  document.getElementById("enrollment").style.display = "none";
  document.getElementById("enrollment-label").style.display = "none";
});
